"""Host tests for the native-cUR (`uUR`) adapters in ``helpers/ur2/decoder.py`` and
``helpers/ur2/encoder.py``.

The real native module only exists on-device, so host pytest normally exercises the
pure-Python ``ur2`` fallback and the native *adapter* branch never runs. Here we inject a
fake ``uUR`` module that models the native binding's **contract** — an int ``DECODER_*``
state from ``receive_part`` (not a bool), a ``.state``/``.result`` decoder with **no**
``is_complete``, and an encoder whose ``fountain_encoder`` has ``seq_len`` but **no**
``restart`` and which has **no** ``current_part`` — while delegating the actual BC-UR work
to the real ``ur2`` engine so the adapters see realistic parts/results. This pins the
adapter glue (state→bool mapping, ``is_complete`` via ``.state``, restart-via-rebuild, the
``uUR.UR`` conversion) on host; byte-level parity vs. real cUR is a separate on-device test.
"""
import importlib
import sys
import types

import pytest

from seedsigner.helpers.ur2.ur import UR as _Ur2UR
from seedsigner.helpers.ur2.ur_decoder import URDecoder as _Ur2Decoder
from seedsigner.helpers.ur2.ur_encoder import UREncoder as _Ur2Encoder
import seedsigner.helpers.ur2.decoder as decoder_mod
import seedsigner.helpers.ur2.encoder as encoder_mod


# Native DECODER_* state codes (values mirror cUR's ur_decoder_state_t).
_OK = 0          # terminal: finished, result available
_PROCESSING = 1  # valid part accepted, need more
_ERROR = 16      # first error state (>=16 are errors)


class _NativeUR:
    """Models uUR.UR — a bare (type, cbor) holder."""
    def __init__(self, type, cbor):
        self.type = type
        self.cbor = cbor


class _NativeURDecoder:
    """Models uUR.URDecoder: receive_part returns an int state, exposes .state/.result,
    and deliberately has NO is_complete (the real native decoder doesn't)."""
    def __init__(self):
        self._real = _Ur2Decoder()

    def receive_part(self, s):
        ok = self._real.receive_part(s)            # ur2 bool
        if self._real.is_complete():
            return _OK
        return _PROCESSING if ok else _ERROR

    @property
    def state(self):
        return _OK if self._real.is_complete() else _PROCESSING

    @property
    def result(self):
        r = self._real.result_message()            # ur2 UR or None
        return None if r is None else _NativeUR(r.type, r.cbor)

    def estimated_percent_complete(self, weight_mixed_frames=False):
        return self._real.estimated_percent_complete(weight_mixed_frames=weight_mixed_frames)


class _NativeFountainEncoder:
    """Models uUR's FountainEncoder wrapper: seq_len only, deliberately NO restart."""
    def __init__(self, real):
        self._real = real

    def seq_len(self):
        return self._real.fountain_encoder.seq_len()


class _NativeUREncoder:
    """Models uUR.UREncoder: ur must be a native UR; deliberately NO current_part and NO
    fountain restart."""
    def __init__(self, ur, max_fragment_len, first_seq_num=0, min_fragment_len=10):
        real_ur = _Ur2UR(ur.type, ur.cbor)
        self._real = _Ur2Encoder(real_ur, max_fragment_len, first_seq_num, min_fragment_len)
        self.fountain_encoder = _NativeFountainEncoder(self._real)

    def next_part(self):
        return self._real.next_part()

    def is_complete(self):
        return self._real.is_complete()


def _make_fake_uUR():
    m = types.ModuleType("uUR")
    m.DECODER_OK = _OK
    m.DECODER_PROCESSING = _PROCESSING
    m.URDecoder = _NativeURDecoder
    m.UREncoder = _NativeUREncoder
    m.UR = _NativeUR
    return m


@pytest.fixture
def native_adapters():
    """Inject the fake native ``uUR`` and reload the seams so their NATIVE adapter branch
    is active; restore the pure-Python fallback on teardown."""
    saved = sys.modules.get("uUR")
    sys.modules["uUR"] = _make_fake_uUR()
    importlib.reload(decoder_mod)
    importlib.reload(encoder_mod)
    try:
        yield decoder_mod.URDecoder, encoder_mod.UREncoder
    finally:
        if saved is None:
            sys.modules.pop("uUR", None)
        else:
            sys.modules["uUR"] = saved
        importlib.reload(decoder_mod)
        importlib.reload(encoder_mod)


def _payload(n=200):
    # ur2's pure-Python fountain pads fragments in place, so the message must be a mutable
    # bytearray (native cUR, being C, doesn't care — this is a fixture detail).
    return bytearray((i * 7 + 1) & 0xFF for i in range(n))


def _ur_parts(ur_type, cbor, max_fragment_len):
    """Real multi-part UR parts for (type, cbor), generated by the pure-Python encoder."""
    enc = _Ur2Encoder(_Ur2UR(ur_type, cbor), max_fragment_len)
    return [enc.next_part() for _ in range(enc.fountain_encoder.seq_len())]


# --- decoder adapter -------------------------------------------------------------------

def test_native_decoder_receive_part_returns_bool_and_completes(native_adapters):
    URDecoder, _ = native_adapters
    cbor = _payload()
    parts = _ur_parts("bytes", cbor, max_fragment_len=30)

    d = URDecoder()
    flags = [d.receive_part(p) for p in parts]

    # Real bools, not the native int state (DECODER_OK == 0 would be falsy if passed through).
    assert all(f is True for f in flags)
    assert d.is_complete() is True                 # via .state, since native has no is_complete()
    assert d.result_message().cbor == cbor


def test_native_decoder_rejects_garbage_without_raising(native_adapters):
    URDecoder, _ = native_adapters
    d = URDecoder()
    assert d.receive_part("this is not a ur part") is False
    assert d.is_complete() is False


def test_native_decoder_estimated_percent_accepts_weight_kwarg(native_adapters):
    URDecoder, _ = native_adapters
    parts = _ur_parts("bytes", _payload(), max_fragment_len=30)
    d = URDecoder()
    d.receive_part(parts[0])
    pct = d.estimated_percent_complete(weight_mixed_frames=True)
    assert 0.0 <= pct <= 1.0


# --- encoder adapter -------------------------------------------------------------------

def test_native_encoder_parts_and_seq_len_match_ur2(native_adapters):
    _, UREncoder = native_adapters
    cbor = _payload()

    adapter = UREncoder(ur=_Ur2UR("bytes", cbor), max_fragment_len=30)
    ref = _Ur2Encoder(_Ur2UR("bytes", cbor), 30)
    n = ref.fountain_encoder.seq_len()

    assert adapter.fountain_encoder.seq_len() == n
    assert [adapter.next_part() for _ in range(n)] == [ref.next_part() for _ in range(n)]


def test_native_encoder_restart_rewinds_to_start(native_adapters):
    _, UREncoder = native_adapters
    adapter = UREncoder(ur=_Ur2UR("bytes", _payload()), max_fragment_len=30)

    first = [adapter.next_part() for _ in range(3)]
    adapter.fountain_encoder.restart()             # native has no rewind -> re-instantiate
    again = [adapter.next_part() for _ in range(3)]

    assert first == again


def test_native_encoder_current_part_reemits_without_advancing(native_adapters):
    _, UREncoder = native_adapters
    adapter = UREncoder(ur=_Ur2UR("bytes", _payload()), max_fragment_len=30)

    p = adapter.next_part()
    assert adapter.current_part() == p             # re-emit last, no advance
    assert adapter.current_part() == p
    assert adapter.next_part() != p                # now it advances


def test_seams_have_no_pure_python_fallback_without_native_module():
    # The ur2 runtime fallback was removed (single-decoder cutover): without uUR the seams
    # resolve to an import-safe placeholder that raises on use, NOT the pure-Python class —
    # so UR-path tests skip rather than silently running pure-Python off-device.
    assert "uUR" not in sys.modules
    assert decoder_mod.URDecoder is not _Ur2Decoder
    assert encoder_mod.UREncoder is not _Ur2Encoder
    with pytest.raises(RuntimeError):
        decoder_mod.URDecoder()
    with pytest.raises(RuntimeError):
        encoder_mod.UREncoder(ur=_Ur2UR("bytes", bytearray(b"x")), max_fragment_len=30)
