"""
Resolution-aware animated-QR density lookup.

Animated (UR / BC-UR fountain) QRs render each QR *module* at an integer number of
screen pixels: ``scale = vertical_resolution // (modules + 2 * quiet_zone)``. So the
real readability knob is **pixels-per-module** (3-6), and the per-frame data budget
(``max_fragment_len`` in bytes) is *derived* from it: for a given panel height, denser
data -> a higher QR version -> more modules -> fewer pixels per module (harder to scan).

``QR_DENSITY_BY_RESOLUTION`` maps ``vertical_resolution -> {px_per_module: max_fragment_len}``.
Each cell is the DENSEST fragment length whose worst-case UR part still renders at
exactly that many integer pixels per module on that panel height. The value is a
*ceiling*: the UR encoder splits the message into equal ``ceil(len / count)`` fragments,
so a small payload may render crisper (more px/module) than the row implies -- the
guarantee is ">= px_per_module", never fewer.

The table is generated by ``tools/qr_density_worksheet.py`` (HEADER=34, quiet_zone=2
modules); that worksheet is the source of truth. Regenerate / extend with:
``PYTHONPATH=src python3 tools/qr_density_worksheet.py [vertical_resolution ...]``.
"""

# Pixels-per-module band exposed on the density slider / setting. Bigger = larger
# modules = easier for a camera to scan (but less data per frame -> more frames).
QR_PX_PER_MODULE_MIN = 3
QR_PX_PER_MODULE_MAX = 6

# vertical_resolution (px) -> {px_per_module: max_fragment_len (bytes)}
# Generated by tools/qr_density_worksheet.py -- do not hand-edit; regenerate instead.
QR_DENSITY_BY_RESOLUTION = {
    240: {6: 23,  5: 63,   4: 133,  3: 299},
    320: {6: 105, 5: 163,  4: 299,  3: 642},
    480: {6: 299, 5: 489,  4: 818,  3: 1557},
    720: {6: 818, 5: 1226, 4: 2009, 3: 2114},
}


def nearest_resolution(vertical_resolution):
    """Nearest supported panel height, so an unlisted panel still resolves a row.

    Ties resolve to the lower (denser-capable) supported resolution by dict order.
    """
    return min(
        QR_DENSITY_BY_RESOLUTION,
        key=lambda supported: abs(supported - vertical_resolution),
    )


def max_fragment_len_for(vertical_resolution, px_per_module):
    """Max UR fragment bytes that guarantees >= ``px_per_module`` at this panel height.

    ``vertical_resolution`` is the real panel height in pixels (an unlisted panel falls
    back to the nearest supported one). ``px_per_module`` is an int in the
    ``QR_PX_PER_MODULE_MIN..MAX`` band (the current setting / live-slider value).
    """
    table = QR_DENSITY_BY_RESOLUTION.get(vertical_resolution)
    if table is None:
        table = QR_DENSITY_BY_RESOLUTION[nearest_resolution(vertical_resolution)]
    return table[px_per_module]
